name: flutter_keyboard_example
description: Flutter Keyboard Example by Casey A. Henson
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  #for keyboard
  intl: ^0.16.0
  sliding_up_panel: ^0.3.6
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  mobx_codegen: ^1.1.0+1
  build_runner: 1.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
